apiVersion: v1
kind: Service
metadata:
  name: solar-system-service
  namespace: solar-system
  labels:
    app: solar-system
spec:
  selector:
    app: solar-system
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 32002    # <-- Use 32001 or any free port
  type: NodePort