apiVersion: v1
kind: Service
metadata:
  name: solar-system-service
  labels:
    app: solar-system
spec:
  selector:
    app: solar-system
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP  # Change to LoadBalancer if you're not using Ingress